import { FormControls } from "src/app/Models/FormControl/formcontrol";

export class StateWiseSummaryControl {
  stateWiseSummaryArray: FormControls[];
  constructor() {
    this.stateWiseSummaryArray = [
      {
        name: "MIN",
        label: "Manual Invoice Number",
        placeholder: "Manual Invoice Number",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "customerName",
        label: "Customer Name",
        placeholder: "Customer Name",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "invoiceDate",
        label: "Invoice Date",
        placeholder: "select Invoice Date",
        type: "date",
        value: new Date(),
        generatecontrol: true,
        disable: false,
        Validations: [],
        additionalData: {
          minDate: new Date(),
        },
      },
      {
        name: "dueDate",
        label: "Due Date",
        placeholder: "select Due Date",
        type: "date",
        value: new Date(),
        generatecontrol: true,
        disable: false,
        Validations: [],
        additionalData: {
          minDate: new Date(),
        },
      },
      {
        name: "unbilledAmount",
        label: "Unbilled Amount",
        placeholder: "Unbilled Amount",
        type: "number",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "remark",
        label: "Remark",
        placeholder: "Remark",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "referenceNo",
        label: "ReferenceNo",
        placeholder: "ReferenceNo",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "tState",
        label: "Trans State",
        placeholder: "Trans State",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "tCity",
        label: "Trans City",
        placeholder: "Trans City",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "tGstin",
        label: "Trans GSTIN",
        placeholder: "Trans GSTIN",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "cState",
        label: "Cust State",
        placeholder: "Cust State",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "cCity",
        label: "Cust City",
        placeholder: "Cust City",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "cGstin",
        label: "Cust GSTIN",
        placeholder: "Cust GSTIN",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "address",
        label: "Address",
        placeholder: "BillingAddress",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "bgl",
        label: "Bill Generation Location",
        placeholder: "Bill Generation Location",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "bsl",
        label: "Bill Submission Location",
        placeholder: "Bill Submission Location",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "bcl",
        label: "Bill Collection Location",
        placeholder: "Bill Collection Location",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "locationFilter",
        label: "Location Filter",
        placeholder: "Location Filter",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "exemptedCategory",
        label: "Exempted Category",
        placeholder: "Exempted Category",
        type: "text",
        value:"",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "unregistered",
        label: "Unregistered",
        placeholder: "",
        type: "toggle",
        value:"",
        generatecontrol: true,
        disable: false,
        Validations: [],
      },
      {
        name: "roundoffAmount",
        label: "Round off Amount",
        placeholder: "",
        type: "toggle",
        value:"",
        generatecontrol: true,
        disable: false,
        Validations: [],
      },
      {
        name: "gstExempted",
        label: "GST Exempted",
        placeholder: "",
        type: "toggle",
        value:"",
        generatecontrol: true,
        disable: false,
        Validations: [],
      },
      {
        name: "roundoffGSTAmount",
        label: "Round off GST Amount",
        placeholder: "",
        type: "toggle",
        value:"",
        generatecontrol: true,
        disable: false,
        Validations: [],
      },
    ];
  }


  getstateWiseSummaryArrayControls() {
    return this.stateWiseSummaryArray;
  }
}
