//this data is not generated and it is hardcoded

export const cnoteMetaData = [
    //Consignor------------------------------------------------------------------------------------------
    {
        "id": 199,
        "Seq": 25,
        "label": "From Master",
        "name": "IsConsignorFromMasterOrWalkin",
        "type": "toggle",
        "dropdown": [],
        "ActionFunction": "IsConsignorFromMasterOrWalkin",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": true,
        "div": "Consignor",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 200,
        "Seq": 31,
        "label": "ConsignorCity",
        "name": "ConsignorCity",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignor",
        "Search": "ConsignorCity",
        "dbCodeName": "MAP_DLOC_CITY"
    },
    {
        "id": 201,
        "Seq": 32,
        "label": "ConsignorPinCode",
        "name": "ConsignorPinCode",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignor",
        "Search": "ConsignorPinCode",
        "dbCodeName": ""
    },

    //Consignee------------------------------------------------------------------------------------------
    {
        "id": 202,
        "Seq": 30,
        "label": "From Master",
        "name": "IsConsigneeFromMasterOrWalkin",
        "type": "toggle",
        "dropdown": [],
        "ActionFunction": "IsConsigneeFromMasterOrWalkin",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": true,
        "div": "Consignee",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 203,
        "Seq": 35,
        "label": "Consignee",
        "name": "ConsigneeCST_NM",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "billingPartyrules",
        "dbCodeName": "BILLINGPARTY_CSGN_CSGE_MSTR"
    },
    {
        "id": 204,
        "Seq": 36,
        "label": "GSTIN NO",
        "name": "ConsigneeGSTINNO",
        "type": "text",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 205,
        "Seq": 37,
        "label": "Adress",
        "name": "ConsigneeCST_ADD",
        "type": "text",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 206,
        "Seq": 38,
        "label": "ConsigneeCity",
        "name": "ConsigneeCity",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "ConsigneeCity",
        "dbCodeName": "MAP_DLOC_CITY"
    },
    {
        "id": 207,
        "Seq": 39,
        "label": "ConsigneePinCode",
        "name": "ConsigneePinCode",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "ConsigneePinCode",
        "dbCodeName": ""
    },
    {
        "id": 208,
        "Seq": 41,
        "label": "Mobile No",
        "name": "ConsigneeCST_MOB",
        "type": "text",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 209,
        "Seq": 40,
        "label": "Telephone No",
        "name": "ConsigneeCST_PHONE",
        "type": "text",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 210,
        "Seq": 41,
        "label": "Yes",
        "name": "IsAppointmentBasedDelivery",
        "type": "radio",
        "dropdown": [],
        "ActionFunction": "displayedAppointment",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "N",
        "div": "AppointmentBasedDelivery",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 211,
        "Seq": 16,
        "label": "IsMarketVehicle",
        "name": "IsMarketVehicle",
        "type": "toggle",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 1,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 212,
        "Seq": 42,
        "label": "Appointment Date ",
        "name": "AppointmentDate",
        "type": "date",
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "AppointmentDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 213,
        "Seq": 43,
        "label": "Name of Person ",
        "name": "NameOfPerson",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "AppointmentDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 214,
        "Seq": 44,
        "label": "Contact Number",
        "name": "AppointmentContactNumber",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "AppointmentDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 215,
        "Seq": 45,
        "label": "Remarks",
        "name": "AppointmentRemarks",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "AppointmentDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 216,
        "Seq": 46,
        "label": "Appointment From Time",
        "name": "AppointmentFromTime",
        "type": "date",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "AppointmentDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 217,
        "Seq": 47,
        "label": "Appointment To Time",
        "name": "AppointmentToTime",
        "type": "date",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "AppointmentDetails",
        "Search": "",
        "dbCodeName": ""
    },


    //ContainerDetails
    {
        "id": 218,
        "Seq": 48,
        "label": "Container No. 1",
        "name": "ContainerNo1",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 219,
        "Seq": 49,
        "label": "Size",
        "name": "ContainerSize1",
        "type": "dropdown",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 220,
        "Seq": 50,
        "label": "Container No. 2",
        "name": "ContainerNo2",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 221,
        "Seq": 51,
        "label": "Size",
        "name": "ContainerSize2",
        "type": "dropdown",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 222,
        "Seq": 52,
        "label": "Booking No",
        "name": "BookingNo",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 223,
        "Seq": 53,
        "label": "Container Type",
        "name": "ContainerType",
        "type": "dropdown",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 224,
        "Seq": 54,
        "label": "Container Capacity",
        "name": "ContainerCapacity",
        "type": "dropdown",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 225,
        "Seq": 55,
        "label": "Seal No",
        "name": "SealNo",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 226,
        "Seq": 56,
        "label": "Shipping Line",
        "name": "ShippingLine",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 227,
        "Seq": 57,
        "label": "Job Order No",
        "name": "JobOrderNo",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 228,
        "Seq": 58,
        "label": "Port",
        "name": "Port",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 229,
        "Seq": 59,
        "label": "Job Order No 2",
        "name": "JobOrderNo2",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 230,
        "Seq": 60,
        "label": "DEO No",
        "name": "DEONo",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": ""
    }




]

