//this data is not generated and it is hardcoded

export const cnoteMetaData = [
    //Consignor------------------------------------------------------------------------------------------
    {
        "id": 199,
        "Seq": 25,
        "label": "From Master",
        "name": "IsConsignorFromMasterOrWalkin",
        "type": "toggle",
        "dropdown": [],
        "ActionFunction": "IsConsignorFromMasterOrWalkin",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": true,
        "div": "Consignor",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 200,
        "Seq": 31,
        "label": "ConsignorCity",
        "name": "ConsignorCity",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignor",
        "Search": "ConsignorCity",
        "dbCodeName": "MAP_DLOC_CITY",
        "useField": "Y"
    },
    {
        "id": 201,
        "Seq": 32,
        "label": "ConsignorPinCode",
        "name": "ConsignorPinCode",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignor",
        "Search": "ConsignorPinCode",
        "dbCodeName": "",
        "useField": "Y"
    },

    //Consignee------------------------------------------------------------------------------------------
    {
        "id": 202,
        "Seq": 30,
        "label": "From Master",
        "name": "IsConsigneeFromMasterOrWalkin",
        "type": "toggle",
        "dropdown": [],
        "ActionFunction": "IsConsigneeFromMasterOrWalkin",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": true,
        "div": "Consignee",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 203,
        "Seq": 35,
        "label": "Consignee",
        "name": "ConsigneeCST_NM",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "ConsigneeDetail",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "billingPartyrules",
        "dbCodeName": "BILLINGPARTY_CSGN_CSGE_MSTR",
        "useField": "Y"
    },
    {
        "id": 204,
        "Seq": 36,
        "label": "GSTIN NO",
        "name": "ConsigneeGSTINNO",
        "type": "text",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 205,
        "Seq": 37,
        "label": "Adress",
        "name": "ConsigneeCST_ADD",
        "type": "text",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 206,
        "Seq": 38,
        "label": "ConsigneeCity",
        "name": "ConsigneeCity",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "ConsigneeCity",
        "dbCodeName": "MAP_DLOC_CITY",
        "useField": "Y"
    },
    {
        "id": 207,
        "Seq": 39,
        "label": "ConsigneePinCode",
        "name": "ConsigneePinCode",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "ConsigneePinCode",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 208,
        "Seq": 41,
        "label": "Mobile No",
        "name": "ConsigneeCST_MOB",
        "type": "text",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 209,
        "Seq": 40,
        "label": "Telephone No",
        "name": "ConsigneeCST_PHONE",
        "type": "text",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 210,
        "Seq": 41,
        "label": "Yes",
        "name": "IsAppointmentBasedDelivery",
        "type": "radio",
        "dropdown": [],
        "ActionFunction": "displayedAppointment",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "N",
        "div": "AppointmentBasedDelivery",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 211,
        "Seq": 16,
        "label": "IsMarketVehicle",
        "name": "IsMarketVehicle",
        "type": "toggle",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 1,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 212,
        "Seq": 42,
        "label": "Appointment Date ",
        "name": "AppointmentDate",
        "type": "date",
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "AppointmentDetails",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 213,
        "Seq": 43,
        "label": "Name of Person ",
        "name": "NameOfPerson",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "AppointmentDetails",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 214,
        "Seq": 44,
        "label": "Contact Number",
        "name": "AppointmentContactNumber",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "AppointmentDetails",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 215,
        "Seq": 45,
        "label": "Remarks",
        "name": "AppointmentRemarks",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "AppointmentDetails",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 216,
        "Seq": 46,
        "label": "Appointment From Time",
        "name": "AppointmentFromTime",
        "type": "date",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "AppointmentDetails",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 217,
        "Seq": 47,
        "label": "Appointment To Time",
        "name": "AppointmentToTime",
        "type": "date",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "AppointmentDetails",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },


    //ContainerDetails
    {
        "id": 218,
        "Seq": 48,
        "label": "Container No. 1",
        "name": "ContainerNo1",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 219,
        "Seq": 49,
        "label": "Size",
        "name": "ContainerSize1",
        "type": "dropdown",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 220,
        "Seq": 50,
        "label": "Container No. 2",
        "name": "ContainerNo2",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 221,
        "Seq": 51,
        "label": "Size",
        "name": "ContainerSize2",
        "type": "dropdown",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 223,
        "Seq": 53,
        "label": "Container Type",
        "name": "ContainerType",
        "type": "dropdown",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 224,
        "Seq": 54,
        "label": "Container Capacity",
        "name": "ContainerCapacity",
        "type": "dropdown",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "ContainerDetails",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    //step3
    {
        "id": 226,
        "Seq": 48,
        "label": "Charged No of Pkg.",
        "name": "TotalChargedNoofPackages",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 230,
        "Seq": 50,
        "label": "Total Declared Value",
        "name": "TotalDeclaredValue",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 231,
        "Seq": 52,
        "label": "ChargedKM",
        "name": "ChargedKM",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 232,
        "Seq": 53,
        "label": "Total Part Quantity",
        "name": "TotalPartQuantity",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 236,
        "Seq": 76,
        "label": "Contents",
        "name": "Contents",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "",
        "Search": "",
        "dbCodeName": "INVOICE_LEVEL_CONTRACT_INVOKE",
        "useField": "Y"
    },
    {
        "id": 235,
        "Seq": 77,
        "label": "Freight Rate",
        "name": "FreightRate",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "",
        "Search": "",
        "dbCodeName": "INVOICE_LEVEL_CONTRACT_INVOKE",
        "useField": "Y"
    },
    {
        "id": 236,
        "Seq": 78,
        "label": "Rate Type",
        "name": "RateType",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "",
        "Search": "",
        "dbCodeName": "INVOICE_LEVEL_CONTRACT_INVOKE",
        "useField": "Y"
    },
    {
        "id": 238,
        "Seq": 19,
        "label": "Freight Amount",
        "name": "FreightAmount",
        "type": "text",
        "ActionFunction": "No",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "",
        "Search": "",
        "dbCodeName": "INVOICE_LEVEL_CONTRACT_INVOKE",
        "useField": "Y"
    },
    {
        "id": 239,
        "Seq": 45,
        "label": "Volumetric",
        "name": "Volumetric",
        "type": "toggle",
        "ActionFunction": "Volumetric",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": false,
        "div": "",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },

    {
        "id": 240,
        "Seq": 70,
        "label": "BcSerialType",
        "name": "BcSerialType",
        "type": "radio",
        "ActionFunction": "BcSerialType",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": "S",
        "div": "BcSerialType",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 241,
        "Seq": 71,
        "label": "From",
        "name": "From",
        "type": "text",
        "ActionFunction": "",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "BcSeries",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 242,
        "Seq": 72,
        "label": "To",
        "name": "To",
        "type": "text",
        "ActionFunction": "",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "BcSeries",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 243,
        "Seq": 73,
        "label": "Bar Code",
        "name": "BarCode",
        "type": "text",
        "ActionFunction": "",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "barcodearray",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    //end
    {
        "id": 245,
        "Seq": 68,
        "label": "EWBDATE",
        "name": "EWBDATE",
        "type": "date",
        "ActionFunction": "",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": 'TodayDate',
        "div": "InvoiceDetails",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    },
    {
        "id": 246,
        "Seq": 69,
        "label": "EWBExpiredDate",
        "name": "EWBEXPIRED",
        "type": "date",
        "ActionFunction": "",
        "Validation": "",
        "frmgrp": 3,
        "display": true,
        "enable": true,
        "defaultvalue": 'TodayDate',
        "div": "InvoiceDetails",
        "Search": "",
        "dbCodeName": "",
        "useField": "Y"
    }


]

