//this data is not generated and it is hardcoded

export const cnoteMetaData = [
    {
        "id": 199,
        "Seq": 31,
        "label": "ConsignorCity",
        "name": "ConsignorCity",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignor",
        "Search": "ConsignorCity",
        "dbCodeName": "MAP_DLOC_CITY"
    },
    {
        "id": 200,
        "Seq": 32,
        "label": "ConsignorPinCode",
        "name": "ConsignorPinCode",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignor",
        "Search": "ConsignorPinCode",
        "dbCodeName": ""
    },

    {
        "id": 201,
        "Seq": 35,
        "label": "Consignee",
        "name": "CST_NM",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "billingPartyrules",
        "dbCodeName": "BILLINGPARTY_CSGN_CSGE_MSTR"
    },
    {
        "id": 202,
        "Seq": 36,
        "label": "GSTIN NO",
        "name": "GSTINNO",
        "type": "text",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 203,
        "Seq": 37,
        "label": "Adress",
        "name": "CST_ADD",
        "type": "text",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 204,
        "Seq": 38,
        "label": "ConsigneeCity",
        "name": "ConsigneeCity",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "ConsigneeCity",
        "dbCodeName": "MAP_DLOC_CITY"
    },
    {
        "id": 205,
        "Seq": 39,
        "label": "ConsigneePinCode",
        "name": "ConsigneePinCode",
        "type": "autodropdown",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "ConsigneePinCode",
        "dbCodeName": ""
    },
    {
        "id": 206,
        "Seq": 40,
        "label": "Mobile No",
        "name": "CST_MOB",
        "type": "text",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "",
        "dbCodeName": ""
    },
    {
        "id": 207,
        "Seq": 41,
        "label": "Telephone No",
        "name": "CST_PHONE",
        "type": "text",
        "dropdown": [],
        "ActionFunction": "No",
        "Validation": "Required",
        "frmgrp": 2,
        "display": true,
        "enable": true,
        "defaultvalue": "",
        "div": "Consignee",
        "Search": "",
        "dbCodeName": ""
    },

]

