import { FormControls } from "src/app/Models/FormControl/formcontrol";

export class OpeningClosingStockReport {
  OpeningClosingStockReportForm: FormControls[];
  constructor() {
    this.OpeningClosingStockReportForm = [
      {
        name: "start",
        label: "Select Data Range",
        placeholder: "Select Date ",
        type: "daterangpicker",
        value: "",
        displaywith: "",
        generatecontrol: true,
        disable: false,
        Validations: [],
        additionalData: {
          support: "end",
        },
      },
      {
        name: "end",
        label: "",
        placeholder: "Select Data Range",
        type: "",
        value: "",
        filterOptions: "",
        autocomplete: "",
        generatecontrol: false,
        disable: true,
        Validations: [],
      },
      {
        name: "",
        label: "",
        placeholder: "",
        type: "",
        value: "",
        generatecontrol: true,
        disable: false,
        Validations: [],
      },
      {
        name: "Location",
        label: "Location",
        placeholder: "",
        type: "dropdown",
        value: [],
        filterOptions: "",
        autocomplete: "",
        displaywith: "",
        Validations: [],
        additionalData: {
          showNameAndValue: false,
        },

        generatecontrol: true,
        disable: false,
      },
      {
        name: "",
        label: "",
        placeholder: "",
        type: "",
        value: "",
        generatecontrol: true,
        disable: false,
        Validations: [],
      },
      {
        name: "",
        label: "",
        placeholder: "",
        type: "",
        value: "",
        generatecontrol: true,
        disable: false,
        Validations: [],
      },
      {
        name: "OR",
        label: "",
        placeholder: "",
        type: "OR",
        value: "",
        generatecontrol: true,
        disable: false,
        Validations: [],
      },
      {
        name: "",
        label: "",
        placeholder: "",
        type: "",
        value: "",
        generatecontrol: true,
        disable: false,
        Validations: [],
      },
      {
        name: "",
        label: "",
        placeholder: "",
        type: "",
        value: "",
        generatecontrol: true,
        disable: false,
        Validations: [],
      },
      {
        name: 'DocumentNO',
        label: "SKU No.",
        placeholder: "Please Enter SKU No comma(,) separated",
        type: 'text',
        value: [],
        generatecontrol: true,
        disable: false,
        Validations: []
    },
    ];
  }
}
