
export class vehicleModel {
    companyId: number;
    vehicleId: number;
    vehicleNo: string;
    vehicleTypeId: any;
    manufactureMonthYear: Date;
    regDate: any;
    modifcationDone: boolean;
    chassisNo: number;
    engineNo: number;
    rcExpiryDate: Date;
    vehicleColor: string;
    bodyType: string;
    ownerCount: number;
    ownerName: string;
    ownerAddress: string;
    ownerPhone: number;
    registrationAuthority: string;
    vehicleTaxUpto: Date;
    vehicleInsuranceCompany: string;
    vehicleInsuraceUpto: Date;
    insurancePolicyNumber: string;
    pucNo: string;
    pucUpto: Date;
    vendorCode: string;
    vendorName: string;
    vendorType: string;
    gpsDeviceEnabled: boolean;
    rcBookNo: string;
    isActive: boolean;
    blackListed: boolean;
    innerDimension: string;
    outerDimension: string;
    payloadCapacity: string;
    id: number;
    entryBy: string;
    entryDate = new Date();
    updateBy: string;
    updateDate: Date;
    conrtl_branch: any;
    vendorcode: any;
    vehroutecd: any;
    gpsProvider: any;
    ftlTypeDesc: any;
    approvedBy: any;
    vendcode: any;
    vehno: any;
    noOfDrivers:any;
    vehregno:any;
    permitValidityDate:any;
    insuranceValidityDate:any;
    unldWt:any;
    gvw:any;
    gpsDeviceId:any;
    capacity:any;
    fitnessValidityDate:any;
    attachedDate:any;
    rate_km:number;
    innerLength:number;
    innerHeight:number;
    innerWidth:number;
    cft:number;
    route:any;
    outerCft :number;
    noOfPackages:any;
    approvedOn:any;
    startDateOfService:any;
    date=new Date()
    controllBranch: any;
    assetName: any;
    vehicleType: any;
    modelNo: any;
    vehicleRCBookNo: any;
    vehicleChasisNo: any;
    certificateNo: any;
    vehicleInsurenceNo: any;
    rtoNo: any;
    outerLength: number;
    outerHeigth: number;
    outerWidth: number;
    regNo: any;
    permitState: any;
    tyreAttached: any;
    constructor(vehicleModel){
        this.vehregno = vehicleModel.vehregno || '';
        this.vehicleType = vehicleModel.vehicleType || '';
        this.controllBranch = vehicleModel.controllBranch || '';
        this.vendorType = vehicleModel.vendorType || '';
        this.vendorName = vehicleModel.vendorName || '';
        this.regDate = vehicleModel.regDate || this.date;
        this.permitValidityDate = vehicleModel.permitValidityDate || this.date;
        this.insuranceValidityDate = vehicleModel.insuranceValidityDate || this.date;
        this.fitnessValidityDate = vehicleModel.fitnessValidityDate || this.date;
        this.attachedDate = vehicleModel.attachedDate || this.date;
        this.rate_km = vehicleModel.rate_km || 0;
        this.innerLength = vehicleModel.innerLength || 0;
        this.innerHeight = vehicleModel.innerHeight || 0;
        this.innerWidth = vehicleModel.innerWidth || 0;
        this.cft = vehicleModel.cft || 0;
        this.approvedOn = vehicleModel.approvedOn || this.date;
        this.startDateOfService = vehicleModel.startDateOfService || this.date;
        this.approvedBy = vehicleModel.approvedBy || '';
        this.isActive = vehicleModel.isActive|| false;
        this.blackListed = vehicleModel.blackListed || false;
    }
}
